import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VidCook",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={{ fontFamily: 'Open Sans' }}>{children}</MantineProvider>
      </body>
    </html>
  );
}
